title: Changqiu Xu's Homepage
page-top-title: Changqiu Xu
top-section-bg-text: IoT Engineering
home-subtitle: Changqiu Xu&ensp;|&ensp;徐长秋
copyright-text: '&copy; Changqiu Xu 2026. All Rights Reserved.'
